### ISSUE TITLE
dev portal web app Not Working in Docker 404

### ISSUE THREAD

**Issue by quantumalchemy** [cpacker/MemGPT#1266]
**Describe the bug**
Running in docker testing dev portal web app / localhost exposing port 8283
also tried a shared network  then just using host 
**Please describe your setup**
- [ ] How did you install memgpt?
Docker:
docker run -it -d --name memgpt --network host -p 8283:8283 -e MEMGPT_SERVER_PASS=xxx -v /home/memgpt:/root python:3.11.6-bookworm
> pip install pymemgpt -U
> linux debian (host) 

server run
Ok can make api calls no problem

root@memgpt:~# memgpt server
Loading config from /root/.memgpt/config
Using existing admin server password from environment.
Loading config from /root/.memgpt/config
User ID: 00000000-0000-0000-0000-0242ac120002
Loading config from /root/.memgpt/config
DEBUG False
Running: uvicorn server:app --host localhost --port 8283
INFO:     Started server process [15]
INFO:     Waiting for application startup.
Writing out openapi_memgpt.json file
Writing out openapi_assistants.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8283 (Press CTRL+C to quit)
INFO:     127.0.0.1:36632 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58850 - "GET /agents/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:34726 - "GET / HTTP/1.1" 404 Not 

### Test ##
http://localhost:8283
or: http://localhost:8283/agents/
{"detail":"Not Found"}

**Comment by sarahwooders** [comment]
@quantumalchemy could you please try again with what's on main? There's been a few fixes.

**Comment by quantumalchemy** [comment]
yeah not hitting the app / or app not loading / server ok on all api calls (json) :
root@26da8caab5bd:/# memgpt server --host 172.19.0.2
Using existing admin server password from environment.
User ID: 00000000-0000-0000-0000-0242ac130002
DEBUG False
Running: uvicorn server:app --host 172.19.0.2 --port 8283
INFO:     Started server process [1118]
INFO:     Waiting for application startup.
Writing out openapi_memgpt.json file
Writing out openapi_assistants.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://172.19.0.2:8283 (Press CTRL+C to quit)
** INFO:     172.19.0.1:37216 - "GET / HTTP/1.1" 404 Not Found
** INFO:     172.19.0.1:53818 - "GET /agents/ HTTP/1.1" 404 Not Found

using docker: python:3.11.6-bookworm container
debian host

**Comment by sarahwooders** [comment]
This should be fixed with the latest 0.3.13 release

**Comment by theocnrds** [comment]
I still have that problem with 0.3.14, although I started server via CLI.
